export const punjabi = {
  filetype: 'mp3',
  filename: [
    'test',
    'q4cp',
    'q5cp',
    'q6cp',
    'q2cp',
    'q3cp',
    'q7cp',
    'q1ap',
    'q2cp',
    'q3ap',
    'q4ap',
  ],
  phonetic: [
    'Sha-tee vich daa-rd hun-dah-ya',
    'daa-rd shu-ru ku-dho ho-iya',
    'saah vee thu-wa-noo char-dah',
    'lum-bah saah leh-kay daa-rd budth-daah-ya',
    'twan-nuu alt-tee awn-nu jee kard-dah-ya',
    'daa-rd too-hee vich vee jand-dah-ya',
    'twan-nuu Chak-rr awn-dah-ya',
    'haa-th naal meh-nu thi-kah daa-rd kith-eh aah',
    'twan-nuu alt-tee awn-nu jee kard-dah-ya',
    'ul-tee aaj twan-nuu aiee ah',
    'twan-nuu ul-tee vich koon suh-gah',
  ],
  originalText: [
    'ਕੀ ਤੁਹਾਨੂੰ ਛਾਤੀ ਵਿੱਚ ਦਰਦ ਹੈ?',
    'ਦਰਦ ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਇਆ?',
    'ਸਾਹ ਲੈਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੈ?',
    'ਜਦੋਂ ਤੁਸੀਂ ਡੂੰਘਾ ਸਾਹ ਲੈਂਦੇ ਹੋ ਤਾਂ ਦਰਦ ਹੋਰ ਵੀ ਵੱਧ ਜਾਂਦਾ ਹੈ?',
    'ਕੀ ਤੁਸੀਂ ਉਲਟੀ ਕਰਨ ਜਾ ਰਹੇ ਹੋ?',
    'ਕੀ ਤੁਹਾਨੂੰ ਪਿੱਠ ਵਿੱਚ ਦਰਦ ਹੈ?',
    'ਕੀ ਤੁਹਾਨੂੰ ਚੱਕਰ ਆ ਰਹੇ ਹਨ',
    'ਮੈਨੂੰ ਇਹ ਦਿਖਾਉਣ ਲਈ ਆਪਣੇ ਹੱਥ ਦੀ ਵਰਤੋਂ ਕਰੋ ਕਿ ਦਰਦ ਕਿੱਥੇ ਹੈ',
    'ਕੀ ਤੁਸੀਂ ਉਲਟੀ ਕਰਨ ਜਾ ਰਹੇ ਹੋ?',
    'ਕੀ ਤੁਸੀਂ ਅੱਜ ਉਲਟੀ ਕੀਤੀ ਹੈ?',
    'ਕੀ ਤੁਹਾਡੀ ਉਲਟੀ ਵਿੱਚ ਖੂਨ ਸੀ?',
  ],
};

export const mandarin = {
  filetype: 'wav',
  filename: [
    'q1cpm',
    'q2cpm',
    'q3cpm',
    'q4cpm',
    'q5cpm',
    'q6cpm',
    'q7cpm',
    'q1apm',
    'q5cpm',
    'q3apm',
    'q4apm',
  ],
  originalText: [
    '你的胸口痛吗?',
    '什么时候开始痛的?',
    '你也呼吸短促吗?',
    '深呼吸的时候疼的更厉害吗?',
    '你感到恶心吗?',
    '疼痛会辐射到你的背部吗?',
    '你头晕吗?',
    '用你的手指给我看哪里疼?',
    '你感到恶心吗?',
    '你今天吐了吗?',
    '你的呕吐物中有血吗?',
  ],
};

export const Arabic = {
  filetype: 'wav',
  filename: [],
  originalText: [
    'هل تعانين من ألم في الصدر',
    'متى بدأ الألم',
    'هل تعاني أيضًا من ضيق في التنفس',
    'هو الألم أسوأ عندما تأخذ نفسا عميقا',
    'هل تشعر بالغثيان',
    'هل ينتشر الألم في ظهرك',
    'أتشعر بالدوار',
    'استخدم يدك لتظهر لي مكان الألم',
    'هل تشعر بالغثيان',
    'هل تقيأت اليوم',
    'هل كان هناك دم في قيئك',
  ],
};
